=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/utilities/websites/csc_core_applications_version_overview/qas/CSCProcesses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2007 sp1 bearbeitet (http://www.altova.com) von C. Merkl (PHOENIX Pharmahandel AG & Co. KG) -->
<!-- Mit XMLSpy v2007 sp1 bearbeitet (http://www.altova.com) von C. Merkl (PHOENIX Pharmahandel AG & Co. KG) -->
<!-- Mit XMLSpy v2007 sp1 bearbeitet (http://www.altova.com) von C. Merkl (PHOENIX Pharmahandel AG & Co. KG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CSCProcesses">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Country" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Process" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="CommandIdentifier" type="xs:string" use="required"/>
									<xs:attribute name="BranchList" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ShortName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="at"/>
									<xs:enumeration value="bg"/>
									<xs:enumeration value="ch"/>
									<xs:enumeration value="de"/>
									<xs:enumeration value="fr"/>
									<xs:enumeration value="hr"/>
									<xs:enumeration value="rs"/>
									<xs:enumeration value="pat"/>
									<xs:enumeration value="pch"/>
									<xs:enumeration value="pfr"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ServerName" type="xs:string" use="required"/>
						<xs:attribute name="UserName" type="xs:string" use="required"/>
						<xs:attribute name="Password" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/utilities/websites/csc_core_applications_version_overview/qas/CSCProcesses.xml
<?xml version="1.0" encoding="UTF-8"?>
<CSCProcesses xsi:noNamespaceSchemaLocation="CSCProcesses.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	
	<Country ShortName="at" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="deli"/>		
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="bg" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />	
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="ch" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />		
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="de" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose"/>		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="ibtorderimport"/>
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor"/>
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>
		<Process CommandIdentifier="umkdrvr"/>		
		<Process CommandIdentifier="zaapunix" />						
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="fr" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose"/>
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="hr" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>				
	<Country ShortName="rs" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pat" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>							
	<Country ShortName="pch" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pfr" ServerName="zqas21" UserName="produser" Password="d5XatpAN1Tm7">			
		<Process CommandIdentifier="aaorderclose"/>				
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor"/>		
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
</CSCProcesses>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/utilities/websites/csc_core_applications_version_overview/prod/CSCProcesses.xml
<?xml version="1.0" encoding="UTF-8"?>
<CSCProcesses xsi:noNamespaceSchemaLocation="CSCProcesses.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	
	<Country ShortName="at" ServerName="oat21" UserName="produser" Password="redR8-Wo3">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="deli"/>		
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="bg" ServerName="obg21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />	
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="ch" ServerName="och21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />		
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="de" ServerName="ode21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="aaorderclose"/>		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="ibtorderimport"/>
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor"/>
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>
		<!--<Process CommandIdentifier="umkdrvr"/>-->
		<Process CommandIdentifier="zaapunix" />						
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="deXML" ServerName="ode23" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="kscserverLN" />				
		<Process CommandIdentifier="kscserverXmlNord" />				
		<Process CommandIdentifier="cscserviceLN" />		
        <Process CommandIdentifier="cscservice70" />		
        <Process CommandIdentifier="cscservice71" />		
        <Process CommandIdentifier="cscservice72" />		
        <Process CommandIdentifier="cscservice73" />		
        <Process CommandIdentifier="cscservice74" />		
        <Process CommandIdentifier="cscservice75" />		
        <Process CommandIdentifier="cscservice76" />		
        <Process CommandIdentifier="cscservice77" />		
	</Country>				
	<Country ShortName="deXML2" ServerName="ode24" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="kscserverLN" />		
		<Process CommandIdentifier="kscserverXmlNord" />		
		<Process CommandIdentifier="cscserviceLN" />		
        <Process CommandIdentifier="cscservice70" />		
        <Process CommandIdentifier="cscservice71" />		
        <Process CommandIdentifier="cscservice72" />		
        <Process CommandIdentifier="cscservice73" />		
        <Process CommandIdentifier="cscservice74" />		
        <Process CommandIdentifier="cscservice75" />		
        <Process CommandIdentifier="cscservice76" />		
        <Process CommandIdentifier="cscservice77" />		        
	</Country>					
	<Country ShortName="deXML3" ServerName="ode25" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="kscserverLN" />		
		<Process CommandIdentifier="kscserverXmlNord" />		
		<Process CommandIdentifier="cscserviceLN" />		
        <Process CommandIdentifier="cscservice70" />		
        <Process CommandIdentifier="cscservice71" />		
        <Process CommandIdentifier="cscservice72" />		
        <Process CommandIdentifier="cscservice73" />		
        <Process CommandIdentifier="cscservice74" />		
        <Process CommandIdentifier="cscservice75" />		
        <Process CommandIdentifier="cscservice76" />		
        <Process CommandIdentifier="cscservice77" />		        
	</Country>		
    <Country ShortName="deXML4" ServerName="ode26" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="kscserverLN" />		
		<Process CommandIdentifier="kscserverXmlNord" />		
		<Process CommandIdentifier="cscserviceLN" />		
        <Process CommandIdentifier="cscservice70" />		
        <Process CommandIdentifier="cscservice71" />		
        <Process CommandIdentifier="cscservice72" />		
        <Process CommandIdentifier="cscservice73" />		
        <Process CommandIdentifier="cscservice74" />		
        <Process CommandIdentifier="cscservice75" />		
        <Process CommandIdentifier="cscservice76" />		
        <Process CommandIdentifier="cscservice77" />		        
	</Country>	    
    <Country ShortName="deXML5" ServerName="ode27" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="kscserverLN" />		
		<Process CommandIdentifier="kscserverXmlNord" />		
		<Process CommandIdentifier="cscserviceLN" />		
        <Process CommandIdentifier="cscservice70" />		
        <Process CommandIdentifier="cscservice71" />		
        <Process CommandIdentifier="cscservice72" />		
        <Process CommandIdentifier="cscservice73" />		
        <Process CommandIdentifier="cscservice74" />		
        <Process CommandIdentifier="cscservice75" />		
        <Process CommandIdentifier="cscservice76" />		
        <Process CommandIdentifier="cscservice77" />		        
	</Country>	            
	<Country ShortName="fr" ServerName="ofr21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="aaorderclose"/>
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="hr" ServerName="ohr21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>				
	<Country ShortName="rs" ServerName="ors21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pat" ServerName="oat21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>							
	<Country ShortName="pch" ServerName="och21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pfr" ServerName="ofr21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="aaorderclose"/>				
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor"/>		
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
</CSCProcesses>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/utilities/websites/csc_core_applications_version_overview/dev/CSCProcesses.xml
<?xml version="1.0" encoding="UTF-8"?>
<CSCProcesses xsi:noNamespaceSchemaLocation="CSCProcesses.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	
	<Country ShortName="at" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="deli"/>		
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="bg" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />	
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>		
	<Country ShortName="ch" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />		
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />		
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="de" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose"/>		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="deli"/>
		<Process CommandIdentifier="ibtorderimport"/>
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor"/>
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>
		<Process CommandIdentifier="umkdrvr"/>		
		<Process CommandIdentifier="zaapunix" />						
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="fr" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose"/>
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha"/>		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>			
	<Country ShortName="hr" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>				
	<Country ShortName="rs" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pat" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />		
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />
		<Process CommandIdentifier="kscserver" />		
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>							
	<Country ShortName="pch" ServerName="zdev21" UserName="devuser" Password="phosix+">			
		<Process CommandIdentifier="aaorderclose" />
		<Process CommandIdentifier="clearreservation" />
		<Process CommandIdentifier="corpha" />		
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor" />
		<Process CommandIdentifier="phadex" />
		<Process CommandIdentifier="phatra" />
		<Process CommandIdentifier="ibtorderimport" />
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
	<Country ShortName="pfr" ServerName="zdev21" UserName="devuser" Password="phosix+">				
		<Process CommandIdentifier="aaorderclose"/>				
		<Process CommandIdentifier="corpha"/>
		<Process CommandIdentifier="kscserver" />				
		<Process CommandIdentifier="phabor"/>		
		<Process CommandIdentifier="phadex" />		
		<Process CommandIdentifier="phatra"/>		
		<Process CommandIdentifier="vbordimport2"/>		
		<Process CommandIdentifier="zaapunix" />
		<Process CommandIdentifier="cscservice" />		
	</Country>						
</CSCProcesses>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/utilities/websites/cscbatches_version_overview/CSCProcesses.xml
<?xml version="1.0" encoding="UTF-8"?>
<CSCProcesses xsi:noNamespaceSchemaLocation="CSCProcesses.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Country ShortName="at" ServerName="oat21" UserName="produser" Password="redR8-Wo3">			
		<Process CommandIdentifier="cscozek" />				
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>		
	<Country ShortName="bg" ServerName="obg21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="cscozek" />		
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>		
	<Country ShortName="ch" ServerName="och21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="cscozek" />		
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>			
	<Country ShortName="de" ServerName="ode21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="cscozek"/>				
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>			
	<Country ShortName="fr" ServerName="ofr21" UserName="produser" Password="redR8-Wo3">		
		<Process CommandIdentifier="cscozek"/>		
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>
	<Country ShortName="hr" ServerName="ohr21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="cscozek" />		
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>					
	<Country ShortName="rs" ServerName="ors21" UserName="produser" Password="redR8-Wo3">
		<Process CommandIdentifier="cscozek" />		
		<Process CommandIdentifier="cscbatchhistory" />				
	</Country>							
</CSCProcesses>
