=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/Covid19XmlViewerBatch/Covid19XmlViewerBatch/MailConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2007 sp1 bearbeitet (http://www.altova.com) von C. Merkl (PHOENIX Pharmahandel AG & Co. KG) -->
<!-- Mit XMLSpy v2007 sp1 bearbeitet (http://www.altova.com) von C. Merkl (PHOENIX Pharmahandel AG & Co. KG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MailConfiguration">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Body" type="xs:string"/>
				<xs:element name="Recipients">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Recipient" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="SMTPServer" type="xs:string" use="required"/>
			<xs:attribute name="Sender" type="xs:string" use="required"/>
			<xs:attribute name="Subject" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/Covid19XmlViewerBatch/Covid19XmlViewerBatch/MailConfigurationNoOrder_Vertrieb.xml
<?xml version="1.0" encoding="UTF-8"?>
<MailConfiguration Subject="Vertrieb - Covid-19 Orders (No new orders found!)" Sender="s.heinlein@phoenixgroup.eu" SMTPServer="denu00smtpint.phoenix.loc" xsi:noNamespaceSchemaLocation="MailConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Body>
Hallo zusammen,

es wurden keine neuen Covid-19-Auftragsdaten für den Vertrieb gefunden.

Viele Grüße	
	</Body>
	<Recipients>
		<Recipient>b.bischof@phoenixgroup.eu</Recipient>		
		<Recipient>p.kalogeras@phoenixgroup.eu</Recipient>		
		<Recipient>d.zdjelar@phoenixgroup.eu</Recipient>			
		<Recipient>s.heinlein@phoenixgroup.eu</Recipient>
		<Recipient>b.bergmann-necker@myphoenix.at</Recipient>
		<Recipient>n.bergmann@myphoenix.at</Recipient>
		<!--<Recipient>s.steinhaeuser@myphoenix.at</Recipient>	-->
		<Recipient>F.SHAHSAVANPOOR@myphoenix.at</Recipient>
		<Recipient>v.mayer@myphoenix.at</Recipient>
		<Recipient>c.witz@myphoenix.at</Recipient> <!-- added 31.03.2025 15:27 -->
	</Recipients>
</MailConfiguration>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/Covid19XmlViewerBatch/Covid19XmlViewerBatch/MailConfigurationNoOrder_KSC.xml
<?xml version="1.0" encoding="UTF-8"?>
<MailConfiguration Subject="Covid-19 Orders (No new orders found!)" Sender="s.heinlein@phoenixgroup.eu" SMTPServer="denu00smtpint.phoenix.loc" xsi:noNamespaceSchemaLocation="MailConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Body>
Hallo zusammen,

es wurden keine neuen Covid-19-Auftragsdaten gefunden.

Viele Grüße	
	</Body>
	<Recipients>
		<Recipient>b.bischof@phoenixgroup.eu</Recipient>		
		<Recipient>p.kalogeras@phoenixgroup.eu</Recipient>		
		<Recipient>d.zdjelar@phoenixgroup.eu</Recipient>		
		<Recipient>s.heinlein@phoenixgroup.eu</Recipient>		
		<Recipient>i.einig@myphoenix.at</Recipient>		
		<Recipient>cid.bestellung@myphoenix.at</Recipient>		
		<!--<Recipient>g.strouhal@myphoenix.at</Recipient>		
		<Recipient>m.volk@myphoenix.at</Recipient>
		<Recipient>b.bergmann-necker@myphoenix.at</Recipient>-->
	</Recipients>
</MailConfiguration>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/Covid19XmlViewerBatch/Covid19XmlViewerBatch/MailConfiguration_Vertrieb.xml
<?xml version="1.0" encoding="UTF-8"?>
<MailConfiguration Subject="Vertrieb - Covid-19 Orders" Sender="s.heinlein@phoenixgroup.eu" SMTPServer="denu00smtpint.phoenix.loc" xsi:noNamespaceSchemaLocation="MailConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Body>
Hallo zusammen,

im Anhang findet ihr die neuesten Covid-19-Auftragsdaten für den Vertrieb.	

Viele Grüße	
	</Body>
	<Recipients>
		<Recipient>b.bischof@phoenixgroup.eu</Recipient>				
		<Recipient>d.zdjelar@phoenixgroup.eu</Recipient>			
		<Recipient>s.heinlein@phoenixgroup.eu</Recipient>
		<Recipient>b.bergmann-necker@myphoenix.at</Recipient>
		<Recipient>n.bergmann@myphoenix.at</Recipient> <!-- added 25.01.2022 11:45 -->		
		<Recipient>F.SHAHSAVANPOOR@myphoenix.at</Recipient>
		<Recipient>v.mayer@myphoenix.at</Recipient> <!-- added 07.08.2023 07:04 -->
		<Recipient>c.witz@myphoenix.at</Recipient> <!-- added 31.03.2025 15:27 -->
	</Recipients>
</MailConfiguration>

=== haythem-dev/long_term_stock/ph.out.csc_core_apps_initial_bef_cpr/dev/doc/Covid19XmlViewerBatch/Covid19XmlViewerBatch/MailConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<MailConfiguration Subject="Covid-19 Orders" Sender="s.heinlein@phoenixgroup.eu" SMTPServer="denu00smtpint.phoenix.loc" xsi:noNamespaceSchemaLocation="MailConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Body>
Hallo zusammen,

im Anhang findet ihr die neuesten Covid-19-Auftragsdaten.	

Viele Grüße	
	</Body>
	<Recipients>
		<Recipient>b.bischof@phoenixgroup.eu</Recipient>				
		<Recipient>d.zdjelar@phoenixgroup.eu</Recipient>		
		<Recipient>s.heinlein@phoenixgroup.eu</Recipient>		
		<Recipient>i.einig@myphoenix.at</Recipient>		
		<Recipient>cid.bestellung@myphoenix.at</Recipient>		
		<Recipient>j.jerson@myphoenix.at</Recipient>		
		<!--<Recipient>g.strouhal@myphoenix.at</Recipient>		
		<Recipient>m.volk@myphoenix.at</Recipient>
		<Recipient>b.bergmann-necker@myphoenix.at</Recipient>-->
	</Recipients>
</MailConfiguration>
